name: Unit tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Setup Python
        uses: actions/setup-python@latest

      - name: "Install dependencies"
        run: "pip install -r requirements.txt"

      - name: "Run tests"
        run: "pytest"